apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://oap:9090
  
  - name: skywalking
    type: apache-skywalking-datasource
    access: proxy
    url: http://oap:12800/graphql
    jsonData:
      URL: http://oap:12800/graphql

  - name: loki
    type: loki
    access: proxy
    url: http://oap:3100
