version: '3'

services:
  mysql:                                            #mysql服务节点
    image: mysql:${MYSQL_TAG}                       #mysql镜像，如果镜像容器没有会去自动拉取
    container_name: mysql                           #容器的名称
    command:                                        #构建容器后所执行的命令
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   #设置root帐号密码
    ports:
      - ${MYSQL_PORT}:3306
    # volumes:
    #  - ${MYSQL_CONFIG_DIR}/data:/var/lib/mysql           #数据文件挂载
    #  - ${MYSQL_CONFIG_DIR}/conf.d:/etc/mysql/conf.d      #配置文件挂载
    #  - ${MYSQL_CONFIG_DIR}/log:/var/log/mysql            #日志文件挂载